// UI action types
export const UI_START_LOADING = 'UI_START_LOADING';
export const UI_STOP_LOADING = 'UI_STOP_LOADING';
export const USER_UI_START_LOADING = 'USER_UI_START_LOADING';
export const USER_UI_STOP_LOADING = 'USER_UI_STOP_LOADING';
export const EMPLOYEES_UI_START_LOADING = 'EMPLOYEES_UI_START_LOADING';
export const EMPLOYEES_UI_STOP_LOADING = 'EMPLOYEES_UI_STOP_LOADING';
export const ABSENTEEISM_UI_START_LOADING = 'ABSENTEEISM_UI_START_LOADING';
export const ABSENTEEISM_UI_STOP_LOADING = 'ABSENTEEISM_UI_STOP_LOADING';
export const ARREARS_UI_START_LOADING = 'ARREARS_UI_START_LOADING';
export const ARREARS_UI_STOP_LOADING = 'ARREARS_UI_STOP_LOADING';
export const PAYSLIPS_UI_START_LOADING = 'PAYSLIPS_UI_START_LOADING';
export const PAYSLIPS_UI_STOP_LOADING = 'PAYSLIPS_UI_STOP_LOADING';

// Authentication action types
export const AUTH_ERROR = 'AUTH_ERROR';
export const AUTH_SET_TOKEN = 'AUTH_SET_TOKEN';
export const AUTH_REMOVE_TOKEN = 'AUTH_REMOVE_TOKEN';

// User action types
export const SET_USER = 'SET_USER';
export const RESET_USER = 'RESET_USER';
export const SET_EMPLOYEE = 'SET_EMPLOYEE';

// Employees action types
export const SET_EMPLOYEES = 'SET_EMPLOYEES';

// Payslips action types
export const SET_PAYSLIPS = 'SET_PAYSLIPS';

// Absenteeism action types
export const SET_ABSENTEEISM = 'SET_ABSENTEEISM';

// Arrears action types
export const SET_ARREARS = 'SET_ARREARS';
